services:
  db:
    image: mariadb:10.11
    restart: always
    command: --event_scheduler=ON
    environment:
      MYSQL_ROOT_PASSWORD: pet_monitoring
    ports:
      - "3306:3306"  # Открывает порт 3306 для доступа с хоста
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Важно: файл должен быть в UTF-8

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"  # Открывает порт 8080 для доступа к phpMyAdmin
    environment:
      PMA_HOST: db  # Подключаемся к сервису db
      PMA_ARBITRARY: 0
    depends_on:
      - db

volumes:
  db_data:

